server:
  port: 8089
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mp_user?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dj.ssm.pojo
  configuration:
    map-underscore-to-camel-case: true
