server:
  port: 8089
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dj.ssm.pojo
  configuration:
    map-underscore-to-camel-case: true
